from .employees.employee_list import employee_list
from .employees.details import employee_details
from .departments.department_list import department_list
from .departments.department_details import department_details
from .trainingprograms.training_program_list import training_program_list
from .trainingprograms.trainingprogram_form import training_program_form
from .home import home
from .auth.logout import logout_user
from .computers.computer_list import computer_list
from .computers.details import computer_details
from .computers.form import computer_form
from .departments.form import department_form